// Self-host Geist and Fraunces.
//
// Two reasons this is worth doing rather than linking Google's CSS. It removes a
// third-party request from the critical path on a site whose pitch is speed —
// and it removes a build-time network dependency that has already failed twice
// in CI, where Turbopack could not fetch Fraunces and the deploy died with
// twelve module-not-found errors.
//
// Google serves one @font-face per unicode-range. Only the latin ranges are
// kept: this site publishes English, and shipping Cyrillic and Vietnamese
// subsets is bytes nobody downloads for content nobody has.
import fs from "node:fs";
import path from "node:path";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
const DIR = "wp/themes/frontpaged/assets/fonts";
fs.mkdirSync(DIR, { recursive: true });

const FAMILIES = [
  ["Geist", "https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&display=swap"],
  ["Fraunces", "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,400&display=swap"],
];

const out = [];
let kept = 0;
let skipped = 0;

for (const [family, url] of FAMILIES) {
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());

  // Each block is preceded by a /* subset */ comment naming the range.
  const blocks = css.split("/*").slice(1);

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    if (!subset.startsWith("latin")) {
      skipped++;
      continue;
    }

    const src = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!src) continue;

    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1].trim() ?? "400";
    const style = block.match(/font-style:\s*([^;]+);/)?.[1].trim() ?? "normal";
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1].trim();

    const file = `${family.toLowerCase()}-${style}-${weight.replace(/\s+/g, "")}-${subset}.woff2`;
    const buffer = Buffer.from(await fetch(src).then((r) => r.arrayBuffer()));
    fs.writeFileSync(path.join(DIR, file), buffer);
    kept++;

    out.push(
      `@font-face {\n` +
        `  font-family: "${family}";\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        // swap, not block: a flash of fallback text beats invisible text, and
        // invisible text is what a font failure looks like to a crawler.
        `  font-display: swap;\n` +
        `  src: url("../fonts/${file}") format("woff2");\n` +
        (range ? `  unicode-range: ${range};\n` : "") +
        `}`
    );
  }
}

fs.writeFileSync(
  "wp/themes/frontpaged/assets/css/fonts.css",
  `/* Generated by wp/migration/fetch-fonts.mjs — do not edit by hand. */\n\n${out.join("\n\n")}\n`
);

const bytes = fs
  .readdirSync(DIR)
  .reduce((n, f) => n + fs.statSync(path.join(DIR, f)).size, 0);
console.log(`  ${kept} latin faces kept, ${skipped} other subsets skipped`);
console.log(`  ${(bytes / 1024).toFixed(0)} KB total`);
